### ISSUE TITLE
Bug: 不能自动检测是否已经安装依赖

### ISSUE THREAD

**Issue by SaarChaffee** [SaarChaffee/koishi-plugin-pixiv-auth#11]

**Comment by Quisperc** [comment]
![Screenshot_20230603_020707.png](https://user-images.githubusercontent.com/126960324/242959724-b481598d-42d7-4e0c-bf92-16f95c1892fc.png)
这应该是我的错误。是puppeteer插件加载出问题了，导致pixiv-auth检测不了。抱歉。

**Comment by SaarChaffee** [comment]
可以在插件配置页面截一张图吗，正常来说应该会项其他插件那样显示xxx插件未安装

**Comment by Quisperc** [comment]
![Screenshot_20230603_020130.png](https://user-images.githubusercontent.com/126960324/243037533-fb3c33ad-ae26-4705-aae6-c3f3c9bda3d3.png)
![Screenshot_20230603_020147.png](https://user-images.githubusercontent.com/126960324/243037550-25b455bf-7d70-4ffa-9b3f-938e6339b4b5.png)
![Screenshot_20230603_020707.png](https://user-images.githubusercontent.com/126960324/243037588-b80ea4bd-d1fe-4bfa-bbc1-8fa6f0202e13.png)
上面是出问题的截图
论坛有人告诉我说是puppeteer插件多开导致的，但我没找到多开的插件（）。我重启koishi之后，puppeteer和pixiv-auth都可以正常加载了
![Screenshot_20230603_020147.png](https://user-images.githubusercontent.com/126960324/243038491-0d96d357-b96e-4a3d-9453-9f483d0a5f66.png)
这是puppeteer配置页面
![Screenshot_20230603_103904.png](https://user-images.githubusercontent.com/126960324/243038541-ff4d86b1-e9e5-4197-a72e-5365d22e674b.png)
这是启用puppeteer的日志，已经没有报错信息了
![Screenshot_20230603_103822.png](https://user-images.githubusercontent.com/126960324/243038192-f1d9f83a-52c3-48f1-b60c-4e6f4edc36db.png)
这是pixiv-auth的配置页面，已经可以正常检测到puppeteer插件是否加载

**Comment by SaarChaffee** [comment]
你要不去koishi提个issue
