### ISSUE TITLE
Bug：入口文件丢失

### ISSUE THREAD

**Issue by Quisperc** [SaarChaffee/koishi-plugin-pixiv-auth#9]
![image](https://github.com/SaarChaffee/koishi-plugin-pixiv-auth/assets/126960324/463e3646-0386-4483-84c2-61c3b6c36be0)
![image](https://github.com/SaarChaffee/koishi-plugin-pixiv-auth/assets/126960324/d8c962b0-4928-4ad0-ae02-80dac24c9de6)

**Comment by SaarChaffee** [comment]
更新插件试试

**Comment by Quisperc** [comment]
已经可以安装，但是貌似不能检测到是否配置puppeteer
